Milestone 4: Contact-form
Xghayor/Portfolio pull request #5
Opened 2023-06-13 22:14 UTC by Xghayor

In this milestone i completed:

1.Added a contact form
2.Added a footer

2023-06-13 23:29 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @Xghayor, @ausiemass  :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Descriptive pull request.
✔️ Follow the correct GitHub flow.
✔️ Commit messages are meaningful.
✔️ Form submission is working fine.

## Required Changes ♻️

***Please kindly check the comments/review below.***

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 23:29 UTC, Tufahel commented on index.html
> +    </div>
- ***Your Design***
![image](https://github.com/Xghayor/Portfolio/assets/60083437/5d8eb9b5-ceba-4f51-bb72-66271036d094)

- [ ] Here I can see you have used two input fields for `name`, as `first name` and `last name`. But I can see in the given template that only the `Full Name` input field is used. Kindly fix this issue.

- ***Given Design***
![image](https://github.com/Xghayor/Portfolio/assets/60083437/4606b5e8-0836-40ad-b653-05bb06707e91)

2023-06-13 23:29 UTC, Tufahel commented on index.html
> +  </div>
- ***Given Design***
![image](https://github.com/Xghayor/Portfolio/assets/60083437/28056ea6-5420-415f-a95b-4b7cd7010e3d)

- For icons, kindly consider the things below to match the given design:
- [ ] Give more margin between the icons.
- [ ] Give more padding/margin between `hr` tag and `footer`
- [ ] Maintain the serial of icons as per the given design.

2023-06-14 14:05 UTC, franclobo requested changes
Hi @Xghayor, 

# ♻️ Required Changes ♻️

![istockphoto-1079018918-612x612](https://github.com/Xghayor/Portfolio/assets/58642949/7d63ed2a-2f3a-4987-9ecd-c0c99d6c93de)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Correct contact form ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 14:05 UTC, franclobo commented on styles.css
> +}
As required by the previous CR: Maintain the serial of icons as per the given design. I suggest adding `flex-flow: row-reverse;` to give the correct order to the social icons to be similar to the Figma design.

| Figma template | Your design | 
|---|---|
| ![image](https://github.com/Xghayor/Portfolio/assets/58642949/ef1f06b7-3386-4ec3-a61d-50c72baa1759) | ![image](https://github.com/Xghayor/Portfolio/assets/58642949/e1a7df73-9084-4731-8ef3-f4b6999ed20e) |

2023-06-14 14:48 UTC, Shisui6 approved these changes
Hi @Xghayor, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights 🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 14:50 UTC, merged